import type { AppLocale } from "@/lib/i18n";

const copy = {
  ru: {
    title: "Рейдовая мастерская",
    tagline: "Готовь рейд. Проверяй. Побеждай.",
    home: "Главная",
    raids: "Рейды",
    tools: "Инструменты",
    stats: "Статистика",
    community: "Сообщество",
    about: "О проекте",
    status: "Мастерская открыта",
    login: "Войти",
    loginUnavailable: "Вход через Battle.net временно недоступен",
    profile: "Личный кабинет",
    navigation: "Навигация",
    check: "Проверить рейд",
    forecast: "Предсказание рейда",
    benefits: "Всё для успешного рейда",
    features: [
      { title: "Анализ состава", lines: ["Найдёт проблемы", "до пула"] },
      { title: "Рекомендации", lines: ["Улучшай шансы", "на победу"] },
      { title: "Актуальные данные", lines: ["Всегда свежая", "информация"] },
      { title: "Больше побед", lines: ["Рейды должны", "приносить радость"] },
    ],
    footer: "Рейдовая мастерская — Инструменты для тех, кто ходит дальше.",
    motto: "Лут. Знания. Сообщество.",
    more: "Больше, чем игра.",
    settings: "Настройки языка",
    statsDescription: "Синхронизируй персонажей через Battle.net, чтобы посмотреть экипировку, уровень предметов и прогресс в личном кабинете.",
    communityDescription: "Собирай единомышленников, находи ближайшие рейды и планируй совместные приключения.",
    aboutDescription: "Рейдовая мастерская помогает подготовиться к рейду: проверить состав и экипировку, найти недостающие усиления и собрать группу. А за предсказаниями заглядывай на Ярмарку Новолуния.",
    openEvents: "Найти рейд",
    createEvent: "Создать событие",
  },
  en: {
    title: "Raid Workshop",
    tagline: "Prepare. Check. Conquer.",
    home: "Home",
    raids: "Raids",
    tools: "Tools",
    stats: "Statistics",
    community: "Community",
    about: "About",
    status: "The workshop is open",
    login: "Sign in",
    loginUnavailable: "Battle.net sign-in is temporarily unavailable",
    profile: "My profile",
    navigation: "Navigation",
    check: "Check your raid",
    forecast: "Raid prediction",
    benefits: "Everything for a successful raid",
    features: [
      { title: "Roster analysis", lines: ["Find problems", "before the pull"] },
      { title: "Recommendations", lines: ["Improve your", "chances of victory"] },
      { title: "Current data", lines: ["Fresh information", "for your next raid"] },
      { title: "More victories", lines: ["Raiding should", "be fun"] },
    ],
    footer: "Raid Workshop — Tools for those who go further.",
    motto: "Loot. Knowledge. Community.",
    more: "More than a game.",
    settings: "Language settings",
    statsDescription: "Sync your characters with Battle.net to see equipment, item level, and progression in your profile.",
    communityDescription: "Find your next group, explore upcoming raids, and plan adventures together.",
    aboutDescription: "Raid Workshop helps you prepare for your next raid: check your roster and equipment, find missing buffs, and get a group together. For a glimpse of your future, visit the Darkmoon Faire.",
    openEvents: "Find a raid",
    createEvent: "Create an event",
  },
};

export function getWorkshopCopy(locale: AppLocale) {
  return copy[locale];
}
