from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "scripts" / "wow_realm_slugs_eu_us.md"
LOCK_PATH = ROOT / "scripts" / "wow_realm_code_lock.json"
TS_PATH = ROOT / "src" / "lib" / "realm-codes.ts"
LUA_PATH = ROOT / "addons" / "RaidReminder" / "RealmCodes.lua"

REGION_CODES = {"EU": ("eu", "e"), "US": ("us", "u")}
ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"
ROW_RE = re.compile(
    r"^\|\s*(EU|US)\s*\|\s*(.*?)\s*\|\s*`([^`]*)`\s*\|\s*`([^`]*)`\s*\|"
)
LUA_REALM_ALIASES = {
    # The addon receives realm names from the local game client. Russian EU
    # clients return localized names, while the source table uses en_GB names.
    "eu": {
        "ashenvale": ["Ясеневый лес"],
        "azuregos": ["Азурегос"],
        "blackscar": ["Черный Шрам"],
        "booty-bay": ["Пиратская Бухта"],
        "borean-tundra": ["Борейская тундра"],
        "deathguard": ["Страж Смерти"],
        "deathweaver": ["Ткач Смерти"],
        "deepholm": ["Подземье"],
        "eversong": ["Вечная Песня"],
        "fordragon": ["Дракономор"],
        "galakrond": ["Галакронд"],
        "goldrinn": ["Голдринн"],
        "gordunni": ["Гордунни"],
        "greymane": ["Седогрив"],
        "grom": ["Гром"],
        "howling-fjord": ["Ревущий фьорд"],
        "lich-king": ["Король-лич"],
        "razuvious": ["Разувий"],
        "soulflayer": ["Свежеватель Душ"],
        "thermaplugg": ["Термоштепсель"],
    },
}


def base36(value: int) -> str:
    if value == 0:
        return "0"

    result = ""
    while value:
        value, remainder = divmod(value, 36)
        result = ALPHABET[remainder] + result
    return result


def parse_source() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []

    for line in SOURCE_PATH.read_text(encoding="utf-8").splitlines():
        match = ROW_RE.match(line)
        if not match:
            continue

        source_region, realm_name, normalized_realm, slug = match.groups()
        region, region_code = REGION_CODES[source_region]
        rows.append(
            {
                "region": region,
                "regionCode": region_code,
                "realmName": realm_name.strip(),
                "normalizedRealm": normalized_realm.strip(),
                "slug": slug.strip(),
            }
        )

    return rows


def load_lock() -> dict[str, dict[str, str]]:
    if not LOCK_PATH.exists():
        return {"eu": {}, "us": {}}

    data = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    return {
        "eu": dict(data.get("eu", {})),
        "us": dict(data.get("us", {})),
    }


def assign_codes(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    lock = load_lock()

    for region in ("eu", "us"):
        region_rows = [row for row in rows if row["region"] == region]
        used = set(lock[region].values())
        next_index = 0

        for row in region_rows:
            slug = row["slug"]
            code = lock[region].get(slug)

            if not code:
                while base36(next_index) in used:
                    next_index += 1

                code = base36(next_index)
                lock[region][slug] = code
                used.add(code)

            row["code"] = code

    LOCK_PATH.write_text(
        json.dumps(lock, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return rows


def js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate_ts(rows: list[dict[str, str]]) -> None:
    lines = [
        "// Generated by scripts/generate_realm_codes.py. Do not edit manually.",
        "",
        'export type RealmRegion = "eu" | "us";',
        'export type RealmRegionCode = "e" | "u";',
        "",
        "export type RealmCodeEntry = {",
        "  code: string;",
        "  normalizedRealm: string;",
        "  realmName: string;",
        "  region: RealmRegion;",
        "  regionCode: RealmRegionCode;",
        "  slug: string;",
        "};",
        "",
        "export const REALM_CODE_TOTAL = %d;" % len(rows),
        "",
        "export const REALM_REGION_BY_CODE: Record<RealmRegionCode, RealmRegion> = {",
        '  e: "eu",',
        '  u: "us",',
        "};",
        "",
        "export const REALM_CODE_BY_REGION: Record<RealmRegion, RealmRegionCode> = {",
        '  eu: "e",',
        '  us: "u",',
        "};",
        "",
        "export const REALM_CODE_ENTRIES = [",
    ]

    for row in rows:
        lines.append(
            "  { code: %s, normalizedRealm: %s, realmName: %s, region: %s, regionCode: %s, slug: %s },"
            % (
                js(row["code"]),
                js(row["normalizedRealm"]),
                js(row["realmName"]),
                js(row["region"]),
                js(row["regionCode"]),
                js(row["slug"]),
            )
        )

    lines.extend(
        [
            "] as const satisfies readonly RealmCodeEntry[];",
            "",
            "const realmByRegionAndCode = new Map<string, RealmCodeEntry>(",
            "  REALM_CODE_ENTRIES.map((entry) => [`${entry.region}:${entry.code}`, entry]),",
            ");",
            "",
            "export function isRealmRegion(value: string): value is RealmRegion {",
            '  return value === "eu" || value === "us";',
            "}",
            "",
            "export function getRealmRegionByCode(value: string | null | undefined) {",
            "  return value === \"e\" || value === \"u\" ? REALM_REGION_BY_CODE[value] : null;",
            "}",
            "",
            "export function getRealmCodeEntry(region: RealmRegion, code: string) {",
            '  return realmByRegionAndCode.get(`${region}:${code.trim().toLowerCase()}`) ?? null;',
            "}",
            "",
            "export function getRealmCodeEntryByRegionCode(",
            "  regionCode: string | null | undefined,",
            "  code: string,",
            ") {",
            "  const region = getRealmRegionByCode(regionCode);",
            "  return region ? getRealmCodeEntry(region, code) : null;",
            "}",
            "",
        ]
    )

    TS_PATH.write_text("\n".join(lines), encoding="utf-8")


def lua(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_aliases(row: dict[str, str]) -> list[str]:
    values = {
        row["realmName"],
        row["normalizedRealm"],
        row["slug"],
        row["realmName"].replace(" ", ""),
        row["normalizedRealm"].replace(" ", ""),
    }

    for alias in LUA_REALM_ALIASES.get(row["region"], {}).get(row["slug"], []):
        values.add(alias)
        values.add(alias.replace(" ", ""))

    ascii_values = set()
    for value in values:
        ascii_values.add(value.lower())
    values.update(ascii_values)

    return sorted(value for value in values if value)


def generate_lua(rows: list[dict[str, str]]) -> None:
    lines = [
        "-- Generated by scripts/generate_realm_codes.py. Do not edit manually.",
        "RaidReminderRealmCodes = {",
        "  byRegion = {",
    ]

    for region, region_code in (("eu", "e"), ("us", "u")):
        lines.append(f"    {region_code} = {{")
        for row in [item for item in rows if item["region"] == region]:
            value = "{ " + ", ".join(
                [lua(row["code"]), lua(row["slug"]), lua(row["realmName"])]
            ) + " }"
            for alias in lua_aliases(row):
                lines.append(f"      [{lua(alias)}] = {value},")
        lines.append("    },")

    lines.extend(
        [
            "  },",
            "}",
            "",
        ]
    )

    LUA_PATH.write_text("\n".join(lines), encoding="utf-8")


def validate(rows: list[dict[str, str]]) -> None:
    if len(rows) != 494:
        raise SystemExit(f"Expected 494 realm rows, found {len(rows)}.")

    for region in ("eu", "us"):
        region_rows = [row for row in rows if row["region"] == region]
        codes = [row["code"] for row in region_rows]
        slugs = [row["slug"] for row in region_rows]

        if len(set(codes)) != len(codes):
            raise SystemExit(f"Duplicate realm code in {region}.")

        if len(set(slugs)) != len(slugs):
            raise SystemExit(f"Duplicate realm slug in {region}.")


def main() -> None:
    rows = assign_codes(parse_source())
    validate(rows)
    generate_ts(rows)
    generate_lua(rows)


if __name__ == "__main__":
    main()
